config/routes.rb
YaffleGuide::Application.routes.draw do
  resources :birds

end

app/models/bird.rb
class Bird < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/birds_controller.rb
class BirdsController < ApplicationController
  # GET /birds
  # GET /birds.xml
  def index
    @birds = Bird.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @birds }
    end
  end

  # GET /birds/1
  # GET /birds/1.xml
  def show
    @bird = Bird.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @bird }
    end
  end

  # GET /birds/new
  # GET /birds/new.xml
  def new
    @bird = Bird.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @bird }
    end
  end

  # GET /birds/1/edit
  def edit
    @bird = Bird.find(params[:id])
  end

  # POST /birds
  # POST /birds.xml
  def create
    @bird = Bird.new(params[:bird])

    respond_to do |format|
      if @bird.save
        format.html { redirect_to(@bird, :notice => 'Bird was successfully created.') }
        format.xml  { render :xml => @bird, :status => :created, :location => @bird }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @bird.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /birds/1
  # PUT /birds/1.xml
  def update
    @bird = Bird.find(params[:id])

    respond_to do |format|
      if @bird.update_attributes(params[:bird])
        format.html { redirect_to(@bird, :notice => 'Bird was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @bird.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /birds/1
  # DELETE /birds/1.xml
  def destroy
    @bird = Bird.find(params[:id])
    @bird.destroy

    respond_to do |format|
      format.html { redirect_to(birds_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/birds_helper.rb
module BirdsHelper
end

app/views/birds/_form.html.erb
<%= form_for(@bird) do |f| %>
  <% if @bird.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bird.errors.count, "error") %> prohibited this bird from being saved:</h2>

      <ul>
      <% @bird.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/birds/edit.html.erb
<h1>Editing bird</h1>

<%= render 'form' %>

<%= link_to 'Show', @bird %> |
<%= link_to 'Back', birds_path %>

app/views/birds/index.html.erb
<h1>Listing birds</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @birds.each do |bird| %>
  <tr>
    <td><%= bird.name %></td>
    <td><%= link_to 'Show', bird %></td>
    <td><%= link_to 'Edit', edit_bird_path(bird) %></td>
    <td><%= link_to 'Destroy', bird, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Bird', new_bird_path %>

app/views/birds/new.html.erb
<h1>New bird</h1>

<%= render 'form' %>

<%= link_to 'Back', birds_path %>

app/views/birds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @bird.name %>
</p>


<%= link_to 'Edit', edit_bird_path(@bird) %> |
<%= link_to 'Back', birds_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>YaffleGuide</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>